### ISSUE TITLE
Release a Calendar app that implements and validates the new import/export WebXDC APIs

### ISSUE THREAD

**Issue by adbenitez** [webxdc/calendar#13]

**Comment by r10s** [comment]
all what's left for that is to tag a release and attach a calendar.xdc there; this will become the new https://github.com/webxdc/calendar/releases/latest/download/calendar.xdc - which is linked on [webxdc.org](https://webxdc.org) as well as on the [upcoming blog post](https://github.com/deltachat/deltachat-pages/pull/688)

version should be `1.0`?

**Comment by ralphtheninja** [comment]
I'd like to consider the type of license we're using and also adding a changelog before releasing 1.0.

Any thoughts behind the current unlicense license? Why not gpl3 or something else?

**Comment by ralphtheninja** [comment]
Side note, if this is pressing to get out I can work on the changelog and add it after the release, np.

**Comment by hpk42** [comment]
FWIW I think GPL3 is ok but i'd prefer MPL, i.e. changes to the code itself need to be published but if it becomes part of something else it's fine if those parts are not published IMO. 
I think it strikes a nice balance but naturally both GPL- and MIT/BSD-enthusiasts will disagree :)

**Comment by r10s** [comment]
k, i think, i tag a release now so that this does not block https://github.com/deltachat/deltachat-pages/pull/688 - improvements on the README are very welcome afterwards as well :)

**Comment by r10s** [comment]
tagged a release and attached calendar.xdx to it: https://github.com/webxdc/calendar/releases/tag/1.0.0
