### ISSUE TITLE
`CREATED` timestamp is wrong

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/calendar#15]
https://github.com/webxdc/calendar/blob/0bafb1002916afc1f4e89f5c16f037c239bba9b6/json-ics.js#L57

should be time of event creation, unlike `DTSTAMP` which is creation time of the ics file as far as I understand https://stackoverflow.com/a/37348467

**Comment by r10s** [comment]
in case this is an optional parameter, we can also just not specify it at all

**Comment by r10s** [comment]
yeah, better merging is a reason to track `CREATED`, indeed

**Comment by r10s** [comment]
thinking it over, it does not really help on merging - as it is the creation timestamp, multiple editors will have the same `CREATED` timestamp, it does not say anything about when things are edited.

so, currently, that property seems not to be important at all. at least it does not play a role for NLNET and also not really for current import/export, removing it from there.
