### ISSUE TITLE
add calendar to webxdc.org

### ISSUE THREAD

**Issue by r10s** [webxdc/calendar#4]
it has a [limited functionality now](https://github.com/webxdc/calendar/pull/2), but the things that are offered work all out in my tests.

anyone else testing the calendar app?

**Comment by WofWca** [comment]
Not thoroughly, but looks alright. I don't mind it getting put on the website.

What concerns me the most is the lack of notifications. Idk if people are gonna expect it to have notifications.

**Comment by r10s** [comment]
> Not thoroughly, but looks alright. I don't mind it getting put on the website.

+1, then let's put i there :)

> What concerns me the most though is the lack of notifications. Idk if people are gonna expect it to have notifications.

i agree, this is one of many missing features - but that does not make the calendar unusable for many other things and we nowhere say that notifications are working nor call the app a "reminder" or so. so i think, this is fine.

my concern was more if there are still things in that just do not work correctly.

**Comment by r10s** [comment]
hm, there is #5 - can someone confirm this bug?
