### ISSUE TITLE
added events not always show immediately

### ISSUE THREAD

**Issue by r10s** [webxdc/calendar#5]
- on sending ios device, added event is shown immediately
- on sending android emulator, added event is shown after re-entering the app only
- on receiving devices, added events are shown after re-entering only

that seem to need some more testing.

**Comment by WofWca** [comment]
> on sending android emulator, added event is shown after re-entering the app only

You mean that you tap "add event" and not displayed on the calendar immediately? Idk, it's not the case for me, on real Android.

> on receiving devices, added events are shown after re-entering only

Also not the case. I have the calendar open on Desktop and Android, and a new even shows up immediately on both devices.

**Comment by r10s** [comment]
> I'm testing in "saved messages"

i am testing in a small group - but i am also wondering, i thought that was working, hm.

**Comment by r10s** [comment]
and i also testing on a real device meanwhile, same issue on android (ios and desktop are fine) with current master resp. 1.34.12 - it might be releted to the recent webxdc patches, androidd 1.34.7 works.

@WofWca which android version are you using?

**Comment by WofWca** [comment]
Version of Delta Chat, that is? 1.34.10.

**Comment by r10s** [comment]
can you try over with 1.34.12

> and now: here is Delta Chat 1.34.12 - choose your flavour and mind your backups:
> - 🍋 https://download.delta.chat/android/beta/deltachat-gplay-release-1.34.12.apk (android, overwrites existing gplay installs, should keep data)
> - 🍉 https://download.delta.chat/android/beta/deltachat-fat-debug-1.34.12.apk (android, can be installed beside gplay)
> - 🍏 https://testflight.apple.com/join/uEMc1NxS (ios, 1.34.12 already available just now)

**Comment by WofWca** [comment]
Yep, it's not good on 1.34.12. When I create an event on Android, it is not shown on Android, but Desktop (1.34.1) does show it immediately.

**Comment by r10s** [comment]
thanks for double-checking

**Comment by r10s** [comment]
closing this here as it is not related to calendar.
