### ISSUE TITLE
think over `X-XDC-COLOR`

### ISSUE THREAD

**Issue by r10s** [webxdc/calendar#52]
allowing random colors, esp. if we show them very prominent as currenty, is a bit thwarting layout wise.

1. maybe better use `CATEGORIES` instead, if we use names as "Red Category", we are even [compatible to outlook](https://support.microsoft.com/en-au/office/create-and-assign-color-categories-a1fde97e-15e1-4179-a1a0-8a91ef89b8dc)  
see https://datatracker.ietf.org/doc/html/rfc5545#page-82  
we could define 3 or 4 categories that are shown exactly the same as now, however, we can change colors later etc. for "normal" events, no categories will be written at all.

2. if we really want to stay with arbitraty colors per event: `COLOR` exists in https://datatracker.ietf.org/doc/html/rfc7986#page-10 - that seems to be better than `X-XDC-COLOR`

but this is no blocker for M1, we can change that at any later point, maybe just go for 

3. make colors nicer

for now.

**Comment by r10s** [comment]
we did 3. for now in #53

**Comment by adbenitez** [comment]
Simple Calendar app on Android uses the field: `X-SMT-CATEGORY-COLOR:-10054206`

**Comment by ralphtheninja** [comment]
Using standardized `CATEGORIES` is probably wise and will make the import and export play nicer with other calendar implementations.

In the add new event dialog we could instead have a drop down list for picking an optional category. This will make it easier to have more categories defined compared to now with buttons to select them.

If an event is added with no category we can just render it with a fallback color that looks nice with the current view. E.g. some light yellow or gray that has a little contrast to the monthly view.
