### ISSUE TITLE
Further i18n

### ISSUE THREAD

**Issue by WofWca** [webxdc/calendar#6]
We did some in 946be39ac03155de44b0b5b222b45d9cb6f7c3bc, but things like "Add event", "Cancel" are still not translated. I don't think it's super important to translate them since you can pretty much guess what each button does.

If we decide to go for it, here is a similar project that is already translated to a lot of languages. Here's ["New event"](https://github.com/nextcloud/calendar/blob/534db17d41083dbb66b1e38dbfb31171971f4e16/l10n/ru.json#L38) string. "Cancel" is also there, "Description", "Event title". We can use it as a git submodule.

**Comment by rosano** [comment]
> If we decide to go for it, here is a similar project that is already translated to a lot of languages. Here's ["New event"](https://github.com/nextcloud/calendar/blob/534db17d41083dbb66b1e38dbfb31171971f4e16/l10n/ru.json#L38) string. "Cancel" is also there, "Description", "Event title". We can use it as a git submodule.

Might be heavy if the other project is large but I love the idea of reusing strings; makes me wonder if there's a [translation memory](https://en.wikipedia.org/wiki/Translation_memory) wiki to facilitate this kind of thing.

**Comment by WofWca** [comment]
> [translation memory](https://en.wikipedia.org/wiki/Translation_memory)

Weblate has this thing: https://docs.weblate.org/en/latest/admin/memory.html, AFAIA it's instance-wide, it's off by default for projects. You get access to it through the "Automatic translations" tab. But I haven't worked with it closely.

**Comment by ralphtheninja** [comment]
Although translations are important in the long run, may I also suggest to try and design the ux in such a way that no language dependent strings are needed?

You could for example use emojis to replace certain actions like cancel as ❌️ and ok as ✅️. Minimizing language dependent strings if used cleverly can both increase the ux and at the same time reduce time spent on maintaining translations. Just my 2 cents.

**Comment by r10s** [comment]
i repeat here what i've written recently somewhere else:

when using icons-only, the meaning should be crystal clear, even to casual users within a second - usually, this applies to very few icons as "trashcan", "home", "search", "print". already does not "cancel" fall into this section and is at least questionable - does  ❌️ mean "cancel" or "delete" or "reset"?

moreover, this will worsen outside consistency - having text buttons in dialogs is what user know and expect. all in all ux would be worsened.

soooo, _if in doubt_,. and this applies here, the easy rule is: an icon with a label is better than an icon alone. there may be reasons to leave out the label (space), but that does not apply here in as a general pattern.

finally, there is also accessibility - and even on desktop, one would expect a descriptive tooltip.

so,  as we cannot replace 100% of texts anyways, it does not really matter if we finally have 20 strings or 5 strings for translation, sth. like  that is needed anyways.

**Comment by ralphtheninja** [comment]
@r10s Those are some really good points. I agree that it must be crystal clear. I merely wanted to mention the usage of icons or emojis. The best with emojis is that they are just text.

**Comment by r10s** [comment]
but it should also be not hard to have a translation system, just a `getString()` taking an id and returning strings from `en.js`, `ru.js`, `sv.js` should be doable within few hours. bonus would be to replace `innerText` from loaded html-files, again by id.

question is: is there sth. good that exist? and where weblate can be attached later?

**Comment by rosano** [comment]
My impression of weblate from almost setting up their cloud version is that popular standard formats should be simple to integrate. I could rent a server to setup the self-hosted version with one-click, if we want to play with it.

I ended up implementing what bjoern suggested in the deltachat/invite project, but the result is a non-standard format.

I was leaning towards https://www.i18next.com for a popular and well-supported format + library.

https://projectfluent.org by Mozilla seems the most thoughtful with avoiding English-centric perspective, but isn't as popular.

**Comment by r10s** [comment]
i think it makes more sense to go for a hosted solution, weblate.org, codeberg or so. i do not have the feeling we want to care for a server on our own. also, the community effect would be larger when using a know  server where already many other ipen source project are on
